CarHub/Controllers/CarAdsController.cs
using CarHub.Service.Core.Interfaces;
using CarHub.Service.Core;
using CarHub.ViewModels.CarAdVMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CarHub.Controllers
{
    public class CarAdsController : Controller
    {
        private readonly ICarAdService carAdService;
        private readonly IFavouriteService favouriteService;

        public CarAdsController(ICarAdService carAdService, IFavouriteService favouriteService)
        {
            this.carAdService = carAdService;
            this.favouriteService = favouriteService;
        }
        public async Task<IActionResult> Index()
        {
            var cars = await carAdService.GetAllAsync();
            return View(cars);
        }
        public async Task<IActionResult> Details(int id)
        {
            var car = await carAdService.GetDetailsAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!string.IsNullOrWhiteSpace(userId))
            {
                car.IsOwner = await carAdService.IsOwnerAsync(id, userId);
                car.IsFavourite = await favouriteService.IsFavouriteAsync(id, userId);
            }

            return View(car);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            var modelForm = await carAdService.GetCreateModelAsync();
            return View(modelForm);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CarAdCreateVM modelForm)
        {
            if (!ModelState.IsValid)
            {
                var vm = await carAdService.GetCreateModelAsync();
                modelForm.Categories = vm.Categories;
                return View(modelForm);
            }

            var ownerId = User.FindFirstValue(ClaimTypes.NameIdentifier)!;

            await carAdService.CreateAsync(modelForm, ownerId);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await carAdService.GetEditModelAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier)!;
            if (!await carAdService.IsOwnerAsync(id, userId))
            {
                return Unauthorized();
            }

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit([FromRoute] int id, CarAdCreateVM inputModel)
        {
            var modelFromDb = await carAdService.GetEditModelAsync(id);
            if (modelFromDb == null) return NotFound();

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier)!;
            if (!await carAdService.IsOwnerAsync(id, userId)) return Unauthorized();

            if (!ModelState.IsValid)
            {
                inputModel.Categories = modelFromDb.Categories;
                return View(inputModel);
            }

            await carAdService.UpdateAsync(inputModel, id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await carAdService.GetDeleteModelAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier)!;
            if (!await carAdService.IsOwnerAsync(id, userId))
            {
                return Unauthorized();
            }

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier)!;
            if (!await carAdService.IsOwnerAsync(id, userId))
            {
                return Unauthorized();
            }

            await carAdService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> MyAds()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier)!;
            var cars = await carAdService.GetMineAsync(userId);
            return View(cars);
        }
    }
}

CarHub/Controllers/FavouritesController.cs
using CarHub.Service.Core.Interfaces;
using CarHub.Service.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CarHub.Controllers
{
    [Authorize]
    public class FavouritesController : Controller
    {
        private readonly IFavouriteService favouriteService;
        public FavouritesController(IFavouriteService favouriteService)
        {
            this.favouriteService = favouriteService;
        }

        [HttpGet]
        public async Task<IActionResult> MyFavourites()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier)!;
            var model = await favouriteService.GetMyFavouritesAsync(userId);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(int carAdId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier)!;
            await favouriteService.AddAsync(carAdId, userId);

            return RedirectToAction("Details", "CarAds", new { id = carAdId });
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int carAdId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier)!;
            await favouriteService.RemoveAsync(carAdId, userId);

            return RedirectToAction("Details", "CarAds", new { id = carAdId });
        }
    }
}

CarHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarHub.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CarAds" asp-action="Index">All Cars</a>
                        </li>
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="CarAds" asp-action="Create">Create Ad</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="CarAds" asp-action="MyAds">My Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Favourites" asp-action="MyFavourites">Favourites</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - CarHub
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>